### ISSUE TITLE
Method [wmenuindex] does not exist on [Harimayco\Menu\Controllers\MenuController]

### ISSUE THREAD

**Issue by webineh** [harimayco/wmenu-builder#10]
how i can manage menu 
http://site.local/wmenuindex
Method [wmenuindex] does not exist on [Harimayco\Menu\Controllers\MenuController]

**Comment by harimayco** [comment]
please make sure you have followed the step by step in usage example.
https://github.com/harimayco/wmenu-builder/blob/master/README.md
