### ISSUE TITLE
Laravel Blade Recursive

### ISSUE THREAD

**Issue by Gialdeb** [harimayco/wmenu-builder#14]
Hi, could you please help me understand how I can show the menu in the view.
I did not understand how I can only show the menu with infinite sub-levels.
I hope in your help and thanks for the excellent work

**Comment by ezequiel9** [comment]
mmm.. I think you need only this.

@extends('admin.layouts.master')

@section('content')

{!! Menu::render() !!}

@endsection


@push('scripts')
    {!! Menu::scripts() !!}
@endpush


And below your js in the layout need put

@stack('scripts') to call the scripts

?
