### ISSUE TITLE
Error publishing migration files

### ISSUE THREAD

**Issue by dandisy** [harimayco/wmenu-builder#16]
May be you have been miss referenced migration files name

$this->publishes([
            __DIR__.'/../migrations/2017_08_11_073824_create_menus_table.php' => database_path('migrations/2017_08_11_073824_create_menus_table.php'),
            __DIR__.'/../migrations/2017_08_11_074006_create_menu_items_table.php' => database_path('migrations/2017_08_11_074006_create_menu_items_table.php'),
        ], 'migrations');

but your migration files are
2017_08_11_073824_create_menus_wp_table.php and 2017_08_11_074006_create_menu_items_wp_table.php

Thx

**Comment by harimayco** [comment]
fixed in v1.3.5
Thank you 👍
