### ISSUE TITLE
is it compatible with laravel 5.6 ??

### ISSUE THREAD

**Issue by kevinRR** [harimayco/wmenu-builder#23]

**Comment by tyndouf** [comment]
Hi, I didn't tested it under Laravel 5.6, but you can make a copy of your Laravel 5.5, modify your composer file to load Laravel 5. and run composer update.

**Comment by sambit-mhptr** [comment]
Made it working on laravel 5.8 latest.
Steps To consider :

1. Use a jquery 2x version. I used [https://code.jquery.com/jquery-2.2.4.min.js](url)

2. Open menu.php in config folder ( config\menu.php ) and change **route_path** to blank and 
   **use_roles** field as false.
3. Open menu-html.blade.php ( views\vendor\harimayco-menu\menu-html.blade.php ) file and search for all $roles variable and replace it with isset($roles).

**Comment by tyndouf** [comment]
Hi,
Thank you for the solution. I w'll test it and leave a comment here to share my experience.
