### ISSUE TITLE
Error Migrate

### ISSUE THREAD

**Issue by chandrastrez** [harimayco/wmenu-builder#24]
`Illuminate\Database\QueryException  : SQLSTATE[42000]: Syntax error or access violation: 1103 Incorrect table name '' (SQL: create table `` (`id` int unsigned not null auto_increment primary key, `name` varchar(191) not null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci')`

Thanks

**Comment by DeveloperOnCall** [comment]
You might have missed the step to publish the config. This is where the table name (and prefix etc) are set up.

``` php artisan vendor:publish --provider="Harimayco\Menu\MenuServiceProvider" ```

Hope that works out the problem.

D
