### ISSUE TITLE
Return an empty array when the menu name not found

### ISSUE THREAD

**Issue by sovichet** [harimayco/wmenu-builder#28]
Hi. I made a change to the below file to return an empty array instead of non-object exception when the menu name is not found via getByName().

File: /vendor/harimayco/laravel-menu/src/WMenu.php

```php
public static function getByName($name)
{
    $menu = Menus::byName($name);
    return is_null($menu) ? [] : self::get($menu->id);
}
```

**Comment by DeveloperOnCall** [comment]
Thanks @sovichet - I have added your change in the next PR
