### ISSUE TITLE
Made it working on laravel 5.8

### ISSUE THREAD

**Issue by BechirAhmed** [harimayco/wmenu-builder#29]
Laravel 5.8
php 7.2

I Got this error when i choose menu to edit, i don't know why, but when i change {!! !!} to {{..}} i got htmlspecialcharacter() error.
if any one know how to fix this
Symfony\Component\Debug\Exception\FatalErrorException thrown with message "Method Illuminate\View\View::__toString() must not throw an exception, caught ErrorException: Undefined property: stdClass::$title (View: D:\WorkSpace\Rim Academy\Designs\RimAcademy\resources\views\vendor\harimayco-menu\menu-html.blade.php)"

**Comment by sambit-mhptr** [comment]
Made it working on laravel 5.8 latest.
Steps To consider :

1. Use a jquery 2x version. I used [https://code.jquery.com/jquery-2.2.4.min.js](url)

2. Open menu.php in config folder ( config\menu.php ) and change **route_path** to blank and 
   **use_roles** field as false.
3. Open menu-html.blade.php ( views\vendor\harimayco-menu\menu-html.blade.php ) file and search for all $roles variable and replace it with isset($roles).

**Comment by BechirAhmed** [comment]
Perfect, thanks @sambit-mhptr so much, I appreciate your help

**Comment by zinnia-visible** [comment]
hello , can't create new menu. show this error message . Uncaught ReferenceError: createnewmenu is not defined
    at HTMLAnchorElement.onclick (menu?action=edit&menu=0:165)
onclick @ menu?action=edit&menu=0:165

please help.

**Comment by batjargale** [comment]
Hi, @zinnia-visible 
I have same problem. Did you fix it?
