### ISSUE TITLE
Installation faild on laravel 5.8

### ISSUE THREAD

**Issue by zanysoft** [harimayco/wmenu-builder#35]
**On installing harimayco/wmenu-builder package i am facing following error:**

> D:\wamp64\www\others\cms>composer require harimayco/laravel-menu
> Using version ^1.3 for harimayco/laravel-menu
> ./composer.json has been updated
> Loading composer repositories with package information
> Updating dependencies (including require-dev)
> Nothing to install or update
> Generating optimized autoload files
> > Illuminate\Foundation\ComposerScripts::postAutoloadDump
>  > @php artisan package:discover --ansi
> 
> In Model.php line 1249:
> 
>   Call to a member function connection() on null
> 
> 
> Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1
> 
> Installation failed, reverting ./composer.json to its original content.

**Comment by DeveloperOnCall** [comment]
This does not look like an error from this package. Please let us know if you are able to install other packages - I am thinking this is unrelated.
