### ISSUE TITLE
Style Issue

### ISSUE THREAD

**Issue by Masoud180** [harimayco/wmenu-builder#38]
Hi
I have a problem with the CSS style.
My admin panel is like this screenshot. 
![5](https://user-images.githubusercontent.com/17505116/59551856-f4698a80-8f94-11e9-86df-8983b67aa79e.png)

I even removed all of my CSSs in my project but the problem still remains.
What should I do?
I'm using Laravel 5.8.

**Comment by DeveloperOnCall** [comment]
@Masoud180 
I restored some css what was previously removed and this seems to have resolved the issue on a fresh install.

I have not, however tested this package on Laravel 5.8x
