### ISSUE TITLE
Parenting doesn't work

### ISSUE THREAD

**Issue by windos757** [harimayco/wmenu-builder#40]
Hello, I'm using laravel-menu with Laravel 5.8 and it looks like the parent is never used.
Whether in the display or in the ajax query.

![image](https://user-images.githubusercontent.com/25634520/60676684-ce425680-9e7f-11e9-8723-b78cc018f211.png)

Plus some styles are totally fucked up

![image](https://user-images.githubusercontent.com/25634520/60676940-75bf8900-9e80-11e9-916a-c79c7c1c644c.png)

Please can you help me ?

**Comment by emtiazzahid** [comment]
did you got any solution for this issue ? :( i am stuck here

**Comment by harimayco** [comment]
fixed in 1.3.10

please update you package then follow this steps :
- delete folder your public/vendor/harimayco-menu
- rerun publish command php artisan vendor:publish --provider="Harimayco\Menu\MenuServiceProvider"

Thank you

**Comment by windos757** [comment]
It works !! thanks a lot :D
