### ISSUE TITLE
cannot use parenting feature

### ISSUE THREAD

**Issue by kodega2016** [harimayco/wmenu-builder#41]

**Comment by emtiazzahid** [comment]
is their any solution you get yet ?

**Comment by harimayco** [comment]
fixed in 1.3.10

please update you package then follow this steps :
- delete folder your public/vendor/harimayco-menu
- rerun publish command php artisan vendor:publish --provider="Harimayco\Menu\MenuServiceProvider"

Thank you

**Comment by emtiazzahid** [comment]
tried 1.3.10 and 1.3.11 also . and removed public/vendor/harimayco-menu folder and published with  php artisan vendor:publish --provider="Harimayco\Menu\MenuServiceProvider" . but same problem. i am using 5.8

**Comment by harimayco** [comment]
@emitiazzahid
have you tried to clear your browser cache?
