### ISSUE TITLE
Don't load resources/views/vendor/harimayco-menu/menu-html.blade.php

### ISSUE THREAD

**Issue by sanvu88** [harimayco/wmenu-builder#43]
When i run command: php artisan vendor:publish --provider="Harimayco\Menu\MenuServiceProvider" and try edit the menu interface in resources/views/vendor/harimayco-menu/menu-html.blade.php, but Package did not load to this file. There are no changes after editing

I use laravel 5.8 on Nginx

**Comment by Denasius** [comment]
I have the same problem. But I have another problem. On the server when accessing the page with the menu, I get an error "View [menu-html] not found." But on the local server everything works well.

**Comment by sanvu88** [comment]
> I have the same problem. But I have another problem. On the server when accessing the page with the menu, I get an error "View [menu-html] not found." But on the local server everything works well.

To fix this you can edit the vendor / harimayco / laravel-menu file / src / WMenu.php:
- Edit line 23 into: return view ('vendor.harimayco-menu.menu-html') -> with ("menulist", $ menulist);
- Edit line 35 to: return view ('vendor.harimayco-menu.menu-html', $ data);
- Edit line 42 to: return view ('vendor.harimayco-menu.scripts');

This is not a good idea, but it helps the package work

**Comment by Denasius** [comment]
> 
> 
> > I have the same problem. But I have another problem. On the server when accessing the page with the menu, I get an error "View [menu-html] not found." But on the local server everything works well.
> 
> To fix this you can edit the vendor / harimayco / laravel-menu file / src / WMenu.php:
> 
>     * Edit line 23 into: return view ('vendor.harimayco-menu.menu-html') -> with ("menulist", $ menulist);
> 
>     * Edit line 35 to: return view ('vendor.harimayco-menu.menu-html', $ data);
> 
>     * Edit line 42 to: return view ('vendor.harimayco-menu.scripts');
> 
> 
> This is not a good idea, but it helps the package work

Worked, thank you!

**Comment by harimayco** [comment]
I have setup wrong package migrate path.
fixed in 1.3.12.
now you can use resources/view/vendor/wmenu/menu-html.blade.php to override the default package view.
please update & rerun : php artisan vendor:publish --provider="Harimayco\Menu\MenuServiceProvider"

Thank you for the report guys 👍

**Comment by teckpy** [comment]
create menu button not work
