### ISSUE TITLE
redirect to /home when adding custom Link

### ISSUE THREAD

**Issue by sanvu88** [harimayco/wmenu-builder#44]
when i create custom Link, after creating the successful menu I was transferred to the home page. I think this problem is caused by Function addcustommenu in menu.js file. After successful creation, window.location = "" will be executed; makes me redirect to home page. I edited it into location.reload (); and everything works well.

Laravel version: 5.8
PHP Version: 7.2
OS: Centos 7.6
Webserver: Nginx

**Comment by harimayco** [comment]
fixed in 1.3.12
please update the package and delete public/vendor/harimayco-menu then re-run publish comand: 
php artisan vendor:publish --provider="Harimayco\Menu\MenuServiceProvider"
thanks for the report 👍
