### ISSUE TITLE
Class 'Menu' not found 

### ISSUE THREAD

**Issue by MikeDynamic** [harimayco/wmenu-builder#46]
I am trying to bring up the builder in my admin page for building a menu. 

My Controller:

```
use Harimayco\Menu\Models\Menus;
use Harimayco\Menu\Models\MenuItems;
........

 public function index()
    {
        return view('admin.menu.index-menu');
    }
```

Blade Template: 

```
inside the blade template

{!! Menu::render() !!}

........

{!! Menu::scripts() !!}

```

I am not sure what else I should do... I have followed exactly. Does the package not create the model Menu? 

Thanks so much

**Comment by MikeDynamic** [comment]
All working... The download of the package was corrupted... all worked after reinstalling the package

**Comment by zinnia-visible** [comment]
hello, admin menu create is ok but not display in frontend. array is empty.
Please help.
