### ISSUE TITLE
Can you change the function name from 'list' to something else?

### ISSUE THREAD

**Issue by rahulsharma841990** [harimayco/wmenu-builder#5]
Kindly change the name of list function, its showing error that we can't set function name list in wmenu.php

Thanks

**Comment by harimayco** [comment]
hi what is the error message?

**Comment by rahulsharma841990** [comment]
![image](https://user-images.githubusercontent.com/6939188/31422146-890b8134-ae69-11e7-914a-36881af50edb.png)

check the screenshot please..

**Comment by harimayco** [comment]
sorry I can't reproduce the error. looks normal in my machine.
you may edit the core file (vendor/harimayco/laravel-menu/src/WMenu.php) to solve your problem.

**Comment by rahulsharma841990** [comment]
Yes, i changed it, and works fine. But next time when i will update the package it will update the function again. And may be there is difference in our php version using php 5.6.19

**Comment by harimayco** [comment]
can you make PR for this?

**Comment by rahulsharma841990** [comment]
PR?

**Comment by monwolf** [comment]
My PR contains this and other minor changes, If you want you can merge it
https://github.com/harimayco/wmenu-builder/pull/6

**Comment by harimayco** [comment]
solved in 1.3
Thanks for your report.
