### ISSUE TITLE
Add support for Laravel 7

### ISSUE THREAD

**Issue by gofatoni** [harimayco/wmenu-builder#50]

**Comment by harimayco** [comment]
Hi Mardianto, I've added laravel 7 support.
you can use v1.4.3 
https://github.com/harimayco/wmenu-builder/releases/tag/1.4.3

Thank you

**Comment by harimayco** [comment]
Hi gofatoni, I've added laravel 7 support.
you can use v1.4.3 
https://github.com/harimayco/wmenu-builder/releases/tag/1.4.3

Thank you
