### ISSUE TITLE
how to install for 5.6

### ISSUE THREAD

**Issue by almi9** [harimayco/wmenu-builder#53]
Hi

Is there any way to install the menu for 5.6?

I run
composer require harimayco/laravel-menu

and I got that error

  Problem 1
    - Conclusion: don't install harimayco/laravel-menu 1.4.3
    - Conclusion: don't install harimayco/laravel-menu 1.4.2
    - Conclusion: don't install harimayco/laravel-menu 1.4.1
    - Conclusion: remove laravel/framework v5.6.39
    - Installation request for harimayco/laravel-menu ^1.4 -> satisfiable by harimayco/laravel-menu[1.4.0, 1.4.1, 1.4.2, 1.4.3].
    - Conclusion: don't install laravel/framework v5.6.39

thanks

**Comment by harimayco** [comment]
Hi I've fix the compability error (composer.json misconfiguration). 
please try again.

Thank you
