### ISSUE TITLE
Route not working..

### ISSUE THREAD

**Issue by iampapaisarkar** [harimayco/wmenu-builder#54]
i just apply all functions. but when i try to update anything. then route not wroking?? please solve issue laravel 7.x
![Annotation 2020-03-16 172652](https://user-images.githubusercontent.com/50805880/76756299-6f253780-67ab-11ea-80d1-45e5e1c7e541.png)
![Annotation 2020-03df16 172652](https://user-images.githubusercontent.com/50805880/76756302-70566480-67ab-11ea-9ec0-e3d679dee45f.png)

**Comment by harimayco** [comment]
looks like you run it from xampp instead of php artisan serve.
can you show me your config file? (config/menu.php)

**Comment by iampapaisarkar** [comment]
sir don't worry. i just solve it few hours ago.. and thank you so much for your response..
