### ISSUE TITLE
Is there any possibility to translate (support localization)

### ISSUE THREAD

**Issue by deekasgtl** [harimayco/wmenu-builder#55]
I need to have localization support in this plugin. Is there any possibility to have this option?

**Comment by harimayco** [comment]
Hi,
currently this package does not support localization by default,
but you can still edit the menu builder interface in resources/views/vendor/wmenu/menu-html.blade.php and put your custom localization there.

**Comment by deekasgtl** [comment]
Great mate. Thank you.
