### ISSUE TITLE
How to for newbie

### ISSUE THREAD

**Issue by osmosiz** [harimayco/wmenu-builder#7]
Hi, I am a newbie with laravel. I've made simple CRUD. And I just installed this wmenu-builder. I did step 1 to 6, and now I don't know what to do after artisan migrate.
I checked my routes/web.php and nothing about menu. Please help me.
Thank you.

**Comment by harimayco** [comment]
the routes are configured inside the package, you don't need to worry about it.
you just need to call the render and scripts function inside your template (.blade.php) file.

### Example
On your view blade file
```php
@extends('app')

@section('contents')
    {!! Menu::render() !!}
@endsection

//YOU MUST HAVE JQUERY LOADED BEFORE menu scripts
@push('scripts')
    {!! Menu::scripts() !!}
@endpush
```

**Comment by osmosiz** [comment]
It works sir. But in my route web.php I added 
`Route::group(['middleware' => config('menu.middleware')], function () {`
...
`});`
from your route file. And it works. Thank you.
